### ISSUE TITLE
Support shady CSS custom styling in SASS

### ISSUE THREAD

**Issue by hotforfeature** [hotforfeature/origami#3]
Like #2 but sassier. There may be limitations with using custom CSS properties in sass.

app.component.ts
```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-poly',
  template: `
    <paper-button>I'm blue!</paper-button>
  `,
  styleUrls: ['./app.component.scss']
})
export class PolyComponent { }
```

app.component.scss
```scss
$ink: blue;

paper-button {
  --paper-button-ink-color: $ink;
}
```
