### ISSUE TITLE
Some CSS mixins in component style NOT working properly in the production build

### ISSUE THREAD

**Issue by first87** [hotforfeature/origami#37]
Currently NOT sure if this problem comes from origami or Angular production mode itself.
The issue was primarily described [here](https://github.com/first87/polymer-chat/issues/11). The demo will be given to reproduce the issue if someone wants.

**Comment by hotforfeature** [comment]
Looks like it's a case of the missing semicolon. I added my comment and fix to https://github.com/first87/polymer-chat/issues/11

**Comment by first87** [comment]
@hotforfeature Thank you for your answer. But it doesn't seem to work in 100% case. I attach a sample source. It works fine on Chrome and FF, but not in Edge (v14.14393) and IE (v11.0.14393.0).

#### Expected Behavior:
![image](https://user-images.githubusercontent.com/20905447/27560338-a6e69e9a-5a78-11e7-8e4e-6c77ad82f3b2.png)

#### Error Behavior in Edge & IE:
Same on both development and production build
![image](https://user-images.githubusercontent.com/20905447/27560366-c39ab5c6-5a78-11e7-96dd-177d20f405da.png)

#### Key changes to style paper-textarea
`src/app/message/message-item.component.css`
```css
.message-input-field {
    --paper-input-container-input-color: var(--app-color-green);
    --paper-input-container-underline: {
        display: none;
    };
    --paper-input-container-underline-focus: {
        display: none;
    };
    @apply --app-word-wrapping;
}
```

What do I still miss?

Thank you in advance.

[demo-to-reproduce.tar.gz](https://github.com/hotforfeature/origami/files/1103507/demo-to-reproduce.tar.gz)

**Comment by hotforfeature** [comment]
@first87 so this is really interesting, and it only seems to affect Edge and IE. Styling by a class or ID CSS selector doesn't seem to work, but the tag does.

`src/app/message/input/message-input.component.css`
```css
paper-textarea {
    --paper-input-container-input-color: var(--app-color-green);
    --paper-input-container-underline: {
        display: none;
    };
    --paper-input-container-underline-focus: {
        display: none;
    };
    @apply --app-word-wrapping;
}
```

I don't know why Edge and IE are doing this. When I have the time, I'll create a Polymer-only repo and see if it's an underlying issue with Polymer/ShadyCSS itself, or if Angular is doing something weird in the mix.

For an immediate workaround, use `paper-textarea` instead of `.message-input-field` to apply the CSS styles.
